version: '3.8'
services:
  composer:
    image: composer:2.1.5
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./src:/app
  app:
    image: php:7.4-cli
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      - SOURCE_DIRECTORY=${SOURCE_DIRECTORY}
      - INPUT_FOLDER=${INPUT_FOLDER}
      - CSV_SEPARATOR=${CSV_SEPARATOR}
    command:
      - /bin/bash
      - -c
      - php index.php \
        --source_directory=${SOURCE_DIRECTORY} \
        --input_folder=${INPUT_FOLDER} \
        --csv_separator=${CSV_SEPARATOR}
  tests:
    image: php:7.4-cli
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

