version: '3.8'
services:
  composer:
    image: composer:2.1.5
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./src:/app
  app:
    image: php:7.4-cli
    volumes:
      - ./src:/app
    working_dir: /app
    environment:
      - INPUT_FOLDER=${INPUT_FOLDER}
    command:
      - /bin/bash
      - -c
      - php index.php ${INPUT_FOLDER}
  tests:
    image: php:7.4-cli
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

